### ISSUE TITLE
An RF Exciter has corrupt data at... ?

### ISSUE THREAD

**Issue by Gabbroboccia** [joekaiser/QuantumFlux#121]
Submitting a bug report? Please fill out the form below the best you can.

*Version:* 
2.0.9
*Mod pack:* 
Vaygrim's Chance 4: VC4
*Summary:*
I get quite a few of these line in the Game output Log:

[21:49:04] [Client thread/INFO]: [CHAT] Whoosh!
[22:02:33] [Client thread/ERROR] [FML]: [@QuantumFlux] HEY YOU! An RF Exciter has corrupt data at BlockPos{x=367, y=113, z=40} The owner will need to replace it.
[22:02:34] [Client thread/ERROR] [FML]: [@QuantumFlux] HEY YOU! An RF Entangler at 377, 110, 32 has corrupt data. The owner needs to replace it
[23:04:47] [Client thread/INFO]: [CHAT] Server Backup started!
____

**What is happening** 
What is happening
I have gone through and replaced all Exciters and Entanglers, even though they still work fine, but I still see this in the Game Output log on the Minecraft Launcher when the game is closed.
It doesnt crash the Client/Server I'm on or seem to cause any other problems I can see. I'd just like to know if its a big problem or maybe I'm just using them incorrectly. Excellent Mod btw.

**How can I reproduce the problem?**

**Comment by joekaiser** [comment]
When you place one down, the user who did it is marked as the "owner". That is how the system builds a network.

That error happens when that user isn't found. If it is happening on logout, it isnt really anything to worry about. As long as they still work when you log back In, don't worry about it.

That being said, if you notice an entangler/excited stood working, check the log for that message and break/replace the block to fix it.

Since you say it works, just ignore it for now. I'll try to make the warning smarter

**Comment by Gabbroboccia** [comment]
Thankyou for the info and speedy reply. Again its a great mod, relatively simple yet potentially very powerful.

**Comment by Gabbroboccia** [comment]
Re-reading the Log it seems to happen when mainly when teleporting.

**Comment by joekaiser** [comment]
Is the chunk always loaded? 

The same code that runs on logout/exit will run when a chunk is unloaded

**Comment by Gabbroboccia** [comment]
No I haven't Chunk loaded the areas.
