### ISSUE TITLE
Quibit clusters should be chainable

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#69]
(Continuation from #6)

Currently, Quibit Clusters are able to push energy to any block that isn't another Quibit Cluster. The reason is because the current implementation would just create a loop between two of them. It would be nice if we could change that.

The obvious solution is configurable sides, but I would like to explore other ways of doing it

**Comment by expl0s1ve** [comment]
How about setting a main block depending on the coords, for example the main block is the one with the highest x,y,z coords, all the energy is stored in that block (with the capacity of sum of all adjacent clusters) and the other cluster blocks mirror it. Well, just a general idea, I'm not great with java, or any programming language for that matter.

**Comment by FantasyTeddy** [comment]
An idea that I had today, was to make the transfer rate of Quibit Clusters dynamic:
When they are almost empty, they can only output a small amount of energy and as they get full, this energy output scales with the contained charge.
This way if you had for example two adjacent Quibit Clusters (one full and one empty), they would exchange energy until they reach an equilibrium. (And if I'm not mistaken this should also hold for more than two Quibit Clusters next to each other.)

This would be easily implemented I think, but I don't know how user-friendly this variable transfer rate would be...

**Comment by expl0s1ve** [comment]
But then a single cluster would be relatively more advantageous because of the ability to output faster with the same amount (not percentage) of power.

**Comment by joekaiser** [comment]
I would have to play with it, but I am not sure if that would be very use friendly. 

I was thinking about bringing in wrench support. The clusters would always auto output to other blocks like they do now, but you would hit them with a wrench for cluster to cluster interaction. Basically switch to send and receive mode per side.

But in the other hand that doesn't seen intuitive

**Comment by FantasyTeddy** [comment]
@expl0s1ve: I don't know if I understand you correctly, but I don't mean to introduce a new type of Quibit Cluster, but to change the existing ones to behave like I tried to explain. Every Cluster would then have the property of a scaled transfer rate.

@joekaiser: I was just trying to think outside of the box, because as you wrote yourself, configurable sides are the obvious choice...
But I also don't know how well my idea would work out. If you want, I could try and implement it and push it to a new experimental branch?!

**Comment by joekaiser** [comment]
I won't stop you, but please don't be offended if k choose not to use it

**Comment by FantasyTeddy** [comment]
Not at all, I may not like it myself to be honest :wink:

**Comment by joekaiser** [comment]
There is some old cluster code in there. I think they are are _N named. Ignore those.

**Comment by FantasyTeddy** [comment]
The deprecated ones? Yes I will ignore them (tomorrow^^).

**Comment by expl0s1ve** [comment]
@FantasyTeddy I may have misunderstood but I see two problems in your design. Let's think of a simple example. Say a cluster can hold 10k RF and output 100RF/tick, and you have a total power reserve of 10k RF. 

If you put a second one next to it they will share power and have 5k RF each, and each one will be able able to output 50RF/tick (If it decreases linearly), so your output per cluster will decrease but total output will remain the same. So you'll have to use more cables connected to all clusters to achieve the same output rate. Unless you mean the output rate variability only holds for the exchange between adjacent clusters but not the other devices and cables, than no problem here.

The second one is, even though they achieve balance (5k RF each in my example), they will continue to output power into each other at half rate therefore not eliminate the loop. Which makes the implementation pointless to begin with. I mean no disrespect or insult, just sharing my opinion. Don't take this the wrong way, and please enlighten me where I'm thinking wrong.

Maybe I'm thinking overly simple but the only solution i can think is something like this.
if (energyCluster1>energyCluster2){
transfer energy from 1 to 2}

**Comment by FantasyTeddy** [comment]
You are right with your example. The problem you describe with the cables in order to achieve the same output rate is exactly what I'm concerned about regarding user-friendliness.
You're also right about the loop which would persist, but this would not really render the implementation pointless in my opinion, because you would still achieve an energy balance between two Clusters (which you don't have at the moment).

Your simple solution could work if there were no cables. If you connect two Quibit Clusters via cable, your simple solution doesn't work anymore or will be far more complicated to implement (if I'm not mistaken).

But the more I think about it, the more I can see why configurable sides are the preferred way to do something like this...

**Comment by expl0s1ve** [comment]
Maybe you can check out the code of the Power Monitor from Ender IO to make it work with cables too. I would but I barely understand anything from them anyway. :D

**Comment by FantasyTeddy** [comment]
Thanks for the suggestion. I might look into that if I find some time :)

**Comment by joekaiser** [comment]
After thinking about it, I am OK with not having them chainable. It ads a certain flaw to the system and will force you down other paths if you need it. 

Maybe the better solution is to have some kind of pipe or wire that can sit between clusters and energy across
