### ISSUE TITLE
Add different sort modes to the Storehouse

### ISSUE THREAD

**Issue by xelrix** [joekaiser/QuantumFlux#77]
Currently, the Storehouse auto sort its inventory.

I would like to suggest that we disable the autosort function, or make it toggled (on/off).
Then we add a button/buttons that sort the inventory on click. Right click to change sort mode, Left click to sort. In case right-click-mode-change is not intuitive, then multiple buttons for all the modes.

Suggested mode would be by id, by mod owner and by oredictionary.

And may I suggest ability to arrange the inventory as normal, in columns, or in rows. Something like what Inventory Tweaks does to items in chest.

**Comment by joekaiser** [comment]
I would rather implement inventory tweaks support than recreate it. I purposely didn't use inventory tweaks because sorting that much stuff had noticeable lag on my PC. 

I will keep this issue open for a bit as a reminder to think about it, but I can't promise I will change it. 

What are you trying to do when you wish you could change the sort? If you are looking for an item then the search would be easier. If you are trying to see all your items from thaumcraft (or some other mod) keep in mind this isn't an inventory management block. It is a way to conviently store items and should be compatible with other inventory management mods

**Comment by xelrix** [comment]
Ah I didn't know inventory sorting has a toll on performance. I thought it would be a simple, convenient feature.

I would like to see this implemented because I don't use AE. I use the storehouse quite liberally. As in changing all of my chests with the Storehouse. A sorting function could make the inventory looks nicer.

Besides, current auto-sort is somewhat imperfect (or buggy?). I could have multiple incomplete stacks (not 64) if i were to break a stack and putting them back.

With that, I would like to take the opportunity to suggest that all stackable items be displayed as 1 stack. If i have 300 breads, Instead of displaying multiple stacks of 8s, it would show 1 bread stack of 300. If I have 300 iron ingots, I'll get 1 stack of iron ingots showing 300 instead of multiple 64s.
I do realize this would make the Storehouse more op than it already is because now, instead of just 999 items, it holds 999 types of items.
I admit I use the storehouse as chest replacement and not as a convenient everything-in-it storage because things look messy. Just an opinion though. Feel free to disregard.

**Comment by joekaiser** [comment]
As of now, this isn't going to be implement. Thanks for the suggestion though
